data:
  path:
    configs: /tmp/sanritools/configs
    tmp: /tmp/sanritools/temp
    libs: /tmp/sanritools/libs
    data: /tmp/sanritools/data
logging:
  path: /tmp/sanritools/logs
maven:
  remoteRepositorys: https://mirrors.huaweicloud.com/repository/maven/
collect:
  ip: localhost
  port: 8085
translate:
  baidu:
    appId: 20181123000238271
    secret:
  youdao:
    appId: 28a343197650d05a
    secret: