spring:
  application:
    name: sanri-tools
  profiles:
    active: company,tomcat,repository,deploy
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  freemarker:
    cache: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 50MB
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
logging:
  level:
    root: info
    com.sanri.tools.modules: debug


