### 上传一个 mybatis xml 文件
POST {{baseUrl}}/mybatis/test/uploadFiles
Content-Type: multipart/form-data; boundary=uploadFiles
Authorization: {{Authorization}}

--uploadFiles
Content-Disposition: form-data; name="file"; filename="BatchMapper.xml"
Content-Type: application/octet-stream

< d:/test/BatchMapper.xml
### 项目列表
GET {{baseUrl}}/mybatis/projects
Authorization: {{Authorization}}

### 项目文件列表
GET {{baseUrl}}/mybatis/test/files
Authorization: {{Authorization}}

### 获取文件内容
GET {{baseUrl}}/mybatis/test/BatchMapper.xml/content
Authorization: {{Authorization}}

### 获取语句列表
GET {{baseUrl}}/mybatis/test/BatchMapper.xml/statementInfos?classLoaderName=222
Authorization: {{Authorization}}

### 根据参数信息获取绑定 sql 语句(无参数)
POST {{baseUrl}}/mybatis/boundSql
Content-Type: application/json
Authorization: {{Authorization}}

{
  "project": "test",
  "fileName": "BatchMapper.xml",
  "classloaderName": "222",
  "statementId": "com.sanri.test.testmybatis.mapper.BatchMapper.testTransaction"
}

### 根据参数信息获取绑定 sql 语句(有参数)
POST {{baseUrl}}/mybatis/boundSql
Content-Type: application/json
Authorization: {{Authorization}}

{
  "project": "test",
  "fileName": "BatchMapper.xml",
  "classloaderName": "222",
  "statementId": "com.sanri.test.testmybatis.mapper.BatchMapper.batchUpdateUseTmpTable",
  "params": [
    {
      "parameterInfo": {
        "name": "batchSubList",
        "type": "java.util.List",
        "parameterTypes": ["com.sanri.test.testmybatis.po.Batch"]
      },
      "value": "[{\"id\":23}]"
    },
    {
      "parameterInfo": {
        "name": "timestamp",
        "type": "long"
      },
      "value": "123"
    }
  ]
}