### 版本管理 - 当前版本
GET {{baseUrl}}/version

### 计算 cron 下次执行时间
POST {{baseUrl}}/cron/nextExecutionTime
Content-Type: application/x-www-form-urlencoded

expression=0 1-6/2 14 ? * ?

### 获取更新记录
GET {{baseUrl}}/system/update/md