### es - 创建新连接
POST {{baseUrl}}/connect/create/elasticsearch
Content-Type: application/json

{
  "address": "10.101.40.127:9200"
}

### es - 数据查询
GET {{baseUrl}}/elasticsearch/search/10.101.40.127/third_out_log_index_2020
Content-Type: application/json

{"query":{"bool":{"must":[],"must_not":[],"should":[{"match_all":{}}]}},"from":0,"size":50,"sort":[{"_score":{"order":"desc"}}],"aggs":{},"version":true}

### health
GET {{baseUrl}}/elasticsearch/cluster/health?connName=192.168.254.131
Authorization: {{Authorization}}

### 索引信息查询
GET {{baseUrl}}/elasticsearch/index/192.168.61.44/indexInfo?indexName=vm-utax-message-2022.08.19
Authorization: {{Authorization}}