### 安全 - 登录
POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "admin",
  "password": "0"
}

> {%
var keyValue = response.headers.toString().split('\n');
var Authorization = undefined;
for (var i=0;i<keyValue.length;i++){
    var one = keyValue[i];
    if(one.startsWith('Authorization')){
       Authorization = one.split(':')[1];
        break;
    }
}
if(Authorization){
    client.global.set("Authorization",Authorization.trim())
}else{
    client.log('未找到 Authorization')
}

%}

#############################管理员维护信息############################################
### 安全-管理员-用户列表
GET {{baseUrl}}/security/admin/users
Authorization: {{Authorization}}

### 安全-管理员-角色列表
GET {{baseUrl}}/security/admin/roles
Authorization: {{Authorization}}

### 安全 - 组织树
GET {{baseUrl}}/security/admin/group/tree
Authorization: {{Authorization}}

### 安全 - 资源列表
GET {{baseUrl}}/security/admin/resources
Authorization: {{Authorization}}

###########################当前用户信息################################################
### 安全 - 退出登录
POST {{baseUrl}}/logout

### 安全 - 当前用户 - 用户名
GET {{baseUrl}}/profile/username
Authorization: {{Authorization}}

### 安全 - 当前用户 - 用户
GET {{baseUrl}}/profile/user
Authorization: {{Authorization}}

### 安全 - 当前用户 - 完整信息
GET {{baseUrl}}/profile
Authorization: {{Authorization}}

### 安全 - 当前用户 - 可授权角色信息查询
GET {{baseUrl}}/profile/accessRoles
Authorization: {{Authorization}}

### 安全 - 当前用户 - 可授权分组信息查询
GET {{baseUrl}}/profile/accessGroups
Authorization: {{Authorization}}

### 安全 - 当前用户 - 可授权资源信息查询
GET {{baseUrl}}/profile/accessResources
Authorization: {{Authorization}}

### 安全 - 当前用户 - 可授权用户信息查询
GET {{baseUrl}}/profile/accessUsers
Authorization: {{Authorization}}

### 安全 - 当前用户 - 可见菜单查询
GET {{baseUrl}}/profile/accessMenus
Authorization: {{Authorization}}

############### 管理操作 ###############################
### 添加组织
POST {{baseUrl}}/security/group/add
Authorization: {{Authorization}}
Content-Type: application/x-www-form-urlencoded

parentGroup=/&childGroup=operator

### 添加角色
POST {{baseUrl}}/security/role/add
Authorization: {{Authorization}}
Content-Type: application/json

{
  "toolRole": {
    "rolename": "op"
  },
  "groups": [
    "/operator"
  ],
  "resources": ["menu_git"]
}

### 添加用户
POST {{baseUrl}}/security/user/add
Authorization: {{Authorization}}
Content-Type: application/json

{
  "toolUser": {
    "username": "sanri"
  },
  "roles": [
    "operator"
  ],
  "groups": ["/operator"]
}

### 安全 - 删除用户
POST {{baseUrl}}/security/user/del
Content-Type: application/x-www-form-urlencoded
Authorization: {{Authorization}}

username=sanri

### 安全 - 删除角色
POST {{baseUrl}}/security/role/del
Content-Type: application/x-www-form-urlencoded
Authorization: {{Authorization}}

rolename=operator

### 安全 - 删除分组
POST {{baseUrl}}/security/group/del
Authorization: {{Authorization}}
Content-Type: application/x-www-form-urlencoded

groupPath=a/b/c/

### 安全 - 用户 - 授权角色
POST {{baseUrl}}/security/user/sanri/grantRoles
Authorization: {{Authorization}}
Content-Type: application/x-www-form-urlencoded

roles=operator,op

### 安全 - 用户 - 授权分组
POST {{baseUrl}}/security/user/sanri/grantGroups
Authorization: {{Authorization}}
Content-Type: application/x-www-form-urlencoded


groups=/core
### 安全 - 角色 - 授权资源
POST {{baseUrl}}/security/role/op/grantGroups
Authorization: {{Authorization}}
Content-Type: application/x-www-form-urlencoded

groups=/core
### 安全 - 角色 - 授权分组
POST {{baseUrl}}/security/role/op/grantResources
Authorization: {{Authorization}}
Content-Type: application/x-www-form-urlencoded

resources=menu_level_1_basedata,menu_git

### 安全 - 用户 - 查看用户可访问用户
GET {{baseUrl}}/security/user/sanri/accessUsers
Authorization: {{Authorization}}
Content-Type: application/x-www-form-urlencoded

### 安全 - 用户 - 查看用户可访问的组织
GET {{baseUrl}}/security/user/sanri/accessGroups
Authorization: {{Authorization}}
Content-Type: application/x-www-form-urlencoded

### 安全 - 用户 - 查看用户可访问的角色
GET {{baseUrl}}/security/user/sanri/accessRoles
Authorization: {{Authorization}}
Content-Type: application/x-www-form-urlencoded

### 安全 - 用户 - 查看用户可以访问的资源
GET {{baseUrl}}/security/user/sanri/accessResources
Authorization: {{Authorization}}
Content-Type: application/x-www-form-urlencoded

### 安全 - 角色 - 查看角色可以访问的资源
GET {{baseUrl}}/security/role/operator/accessResources
Authorization: {{Authorization}}
Content-Type: application/x-www-form-urlencoded