###############################元数据信息##############################################
### 获取数据库连接列表
GET {{baseUrl}}/security/connect/database/connects
Authorization: {{Authorization}}

### 获取数据库连接名列表
GET {{baseUrl}}/security/connect/database/connectNames
Authorization: {{Authorization}}

### 获取 clientInfo
GET {{baseUrl}}/db/metadata/clientInfo?connName=61.71
Authorization: {{Authorization}}

### 获取 catalogs
GET {{baseUrl}}/db/metadata/catalogs?connName=61.71postgre
Authorization: {{Authorization}}

### 获取 schemas
GET {{baseUrl}}/db/metadata/schemas?connName=61.71postgre
Authorization: {{Authorization}}

### 获取指定 catalog 的 schemas
GET {{baseUrl}}/db/metadata/filterSchemas?connName=61.71postgre&catalog=
Authorization: {{Authorization}}

### 获取数据表
GET {{baseUrl}}/db/metadata/tables?connName=61.71postgre&catalog=postgres&schema=mm
Authorization: {{Authorization}}

### 搜索表
GET {{baseUrl}}/db/metadata/searchTables?connName=localhost&catalog=anta&searchSchema=table&keyword=eims
Authorization: {{Authorization}}

### 单表元数据信息
GET {{baseUrl}}/db/metadata/table?connName=eims_oracle&namespace.schema=EAM_TEST&tableName=EIMS_IMAGE
Authorization: {{Authorization}}

### 元数据文档生成
GET {{baseUrl}}/db/doc/export?connName=localhost&catalog=anta&searchSchema=table&keyword=eims
Authorization: {{Authorization}}

### 元数据比对
POST {{baseUrl}}/db/metadata/compare
Content-Type: application/json
Authorization: {{Authorization}}

{
  "baseConnName": "localhost",
  "baseNamespace": {
    "catalog": "anta"
  },
  "compareConnName": "61.71",
  "compareNamespace": {
    "catalog": "eam"
  }
}

### 元数据比对生成 sql 列表
POST {{baseUrl}}/db/metadata/compare/changeSqls
Content-Type: application/json
Authorization: {{Authorization}}

{
  "baseConnName": "localhost",
  "baseNamespace": {
    "catalog": "anta"
  },
  "compareConnName": "61.71",
  "compareNamespace": {
    "catalog": "eam"
  }
}
############################表标记扩展元数据##################################################
### 获取常用标记
GET {{baseUrl}}/db/metadata/extend/mark/tags
Authorization: {{Authorization}}

### 标记表-标记表
POST {{baseUrl}}/db/metadata/extend/mark/config/localhost/tableMark
Content-Type: application/json
Authorization: {{Authorization}}

[
  {
    "actualTableName": {
      "namespace": {
        "catalog": "anta",
        "schema": null
      },
      "tableName": "eims_image"
    },
    "tags": [
      "biz"
    ]
  }
]

### 标记表-获取表标记
GET {{baseUrl}}/db/metadata/extend/mark/tableTags?connName=localhost&namespace.catalog=anta&tableName=eims_image
Authorization: {{Authorization}}

### 标记表-查找某个标记的表
GET {{baseUrl}}/db/metadata/searchTables?connName=localhost&catalog=anta&searchSchema=tag&keyword=biz
Authorization: {{Authorization}}

######################表关系扩展元数据#################################
### 表关系 - 配置表关系
POST {{baseUrl}}/db/metadata/extend/relation/config
Content-Type: application/json
Authorization: {{Authorization}}

{
  "connName": "61.71",
  "namespace": {
    "catalog": "eam"
  },
  "tableRelations": [
    {
      "sourceTableName": "eims_image",
      "targetTableName": "eims_invoices",
      "sourceColumnName": "id",
      "targetColumnName": "imageId",
      "relation": "ONE_ONE"
    },
    {
      "sourceTableName": "eims_invoices",
      "targetTableName": "eims_invoices_detail",
      "sourceColumnName": "invoicenumber",
      "targetColumnName": "invoice_num",
      "relation": "ONE_MANY"
    },
    {
      "sourceTableName": "eims_scantask",
      "targetTableName": "eims_image",
      "sourceColumnName": "billnumber",
      "targetColumnName": "document_code",
      "relation": "ONE_MANY"
    },
    {
      "sourceTableName": "eims_scantask",
      "targetTableName": "eims_invoices",
      "sourceColumnName": "billnumber",
      "targetColumnName": "billnumber",
      "relation": "ONE_MANY"
    }
  ]
}

### 数据库 - 表关系 - 通过 sql 来配置表关系
POST {{baseUrl}}/db/metadata/extend/relation/config/fromSql
Content-Type: application/json
Authorization: {{Authorization}}

{
  "connName": "localhost",
  "namespace": {
    "catalog": "anta"
  },
  "relationSqls": [
    {
      "sql": "SELECT * FROM EIMS_IMAGE EI LEFT JOIN EIMS_INVOICES EI2 ON ei.ID  = ei2.IMAGEID LEFT JOIN EIMS_INVOICES_DETAIL EID ON eid.INVOICE_NUM  = ei2.INVOICENUMBER inner JOIN EIMS_SCANTASK ES ON es.BILLNUMBER  = ei.DOCUMENT_CODE ",
      "relation": "ONE_ONE"
    }
  ]
}

### 数据库 - 表关系 - 查询表引用的关系
GET {{baseUrl}}/db/metadata/extend/relation/parents?connName=localhost&namespace.catalog=anta&tableName=eims_invoices
Authorization: {{Authorization}}

### 数据库 - 表关系  - 查询表的下级引用
GET {{baseUrl}}/db/metadata/extend/relation/childs?connName=localhost&namespace.catalog=anta&tableName=EIMS_IMAGE
Authorization: {{Authorization}}

### 数据库 - 表关系  - 查询数据表的被依赖项调用
GET {{baseUrl}}/db/metadata/extend/relation/hierarchy?connName=localhost&namespace.catalog=anta&tableName=eims_image
Authorization: {{Authorization}}

### 数据库 - 表关系 - 查询表的依赖项调用
GET {{baseUrl}}/db/metadata/extend/relation/superTypes?connName=localhost&namespace.catalog=anta&tableName=eims_invoices
Authorization: {{Authorization}}

#############################表数据随机生成##############################################
### 数据库 - 数据  - 检查脏数据
GET {{baseUrl}}/db/data/checkDirtyData?connName=61.71&catalog=eam
Authorization: {{Authorization}}

### 数据库 - 数据 - 单表随机数据生成
POST {{baseUrl}}/db/data/singleTableRandomData
Content-Type: application/json
Authorization: {{Authorization}}

{
  "connName": "localhost",
  "actualTableName": {
    "namespace": {
      "catalog": "test"
    },
    "tableName": "test_index"
  },
  "size": 120,
  "columnMappers": [
    {
      "columnName": "title",
      "random": "T(com.sanri.tools.modules.core.utils.RandomUtil).chinese(64,null)"
    },
    {
      "columnName": "idcard",
      "random": "T(com.sanri.tools.modules.core.utils.RandomUtil).idcard()"
    },
    {
      "columnName": "age",
      "random": "T(org.apache.commons.lang3.RandomUtils).nextInt(1,140)"
    },
    {
      "columnName": "author",
      "random": "T(com.sanri.tools.modules.core.utils.RandomUtil).chinese(32,null)"
    },
    {
      "columnName": "report_time",
      "random": "T(org.apache.commons.lang3.time.DateFormatUtils).ISO_8601_EXTENDED_DATETIME_FORMAT.format(T(com.sanri.tools.modules.core.utils.RandomUtil).date())"
    }
  ]
}

### 数据库 - 数据 - 单表随机数据(调试)
POST {{baseUrl}}/db/data/singleTableRandomData
Content-Type: application/json
Authorization: {{Authorization}}

{"connName":"localhost","actualTableName":{"namespace":{"catalog":"mobile"},"tableName":"t_user","fullName":"mobile..t_user"},"columnMappers":[{"columnName":"account","random":"T(com.sanri.tools.modules.core.utils.RandomUtil).username()"},{"columnName":"password","fixed":"1234"}],"size":100}

### 数据库 - 数据 - 单表随机数据生成(关联其它表)
POST {{baseUrl}}/db/data/singleTableRandomData
Content-Type: application/json
Authorization: {{Authorization}}

{
  "connName": "localhost",
  "actualTableName": {
    "namespace": {
      "catalog": "test"
    },
    "tableName": "emp"
  },
  "size": 100,
  "columnMappers": [
    {
      "columnName": "empno",
      "random": "T(org.apache.commons.lang3.RandomStringUtils).randomNumeric(4)"
    },
    {
      "columnName": "ename",
      "random": "T(com.sanri.tools.modules.core.utils.RandomUtil).chinese(5,null)"
    },
    {
      "columnName": "deptno",
      "sql": "select deptno from test.dept"
    }
  ]
}

### 数据库 - 数据 - 导入数据
POST {{baseUrl}}/db/data/import/excel
Content-Type: multipart/form-data; boundary=importData
Authorization: {{Authorization}}

--importData
Content-Disposition: form-data; name="excel"; filename="acc_auth_history_record.xlsx"
Content-Type: application/octet-stream

< D:/20210429backup/ECS实操案例_V4.0_20201120.xlsx
--importData
Content-Disposition: form-data; name="config"
Content-Type: application/json

{
"connName": "localhost",
"actualTableName": {
   "namespace": {
      "catalog": "test"
    },
    "tableName": "test_index"
},
"startRow": 2,
"mapping": [
    {
      "columnName": "title",
      "index": 3
    },{
      "columnName": "author",
      "index": 2
    },
    {
      "columnName": "idcard",
      "random": "T(com.sanri.tools.modules.core.utils.RandomUtil).idcard()"
    },
    {
      "columnName": "age",
      "random": "T(org.apache.commons.lang3.RandomUtils).nextInt(1,140)"
    },
    {
      "columnName": "report_time",
      "random": "T(org.apache.commons.lang3.time.DateFormatUtils).ISO_8601_EXTENDED_DATETIME_FORMAT.format(T(com.sanri.tools.modules.core.utils.RandomUtil).date())"
    }
 ]
}

### 数据表 - 数据 - 导出数据预览
POST {{baseUrl}}/db/data/exportPreview
Content-Type: application/json
Authorization: {{Authorization}}

{
  "connName": "localhost",
  "namespace": {
    "catalog": "test"
  },
  "sqls": ["select * from test_index"],
  "traceId":"abcdefg"
}

### 数据表 - 数据 - 导出数据
POST {{baseUrl}}/db/data/exportData
Content-Type: application/json
Authorization: {{Authorization}}

{
  "connName": "localhost",
  "namespace": {
    "catalog": "test"
  },
  "sqls": ["select * from test_index"],
  "traceId": "abc"
}

### 数据表 - 数据 - 执行查询
POST {{baseUrl}}/db/data/executeQuery
Content-Type: application/json
Authorization: {{Authorization}}

{
  "connName": "localhost",
  "namespace": {
    "catalog": "test"
  },
  "sqls": ["select * from test_index limit 10"],
  "traceId": "abc"
}

### 数据表 - 数据 - 执行 ddl
POST {{baseUrl}}/db/data/executeUpdate
Content-Type: application/json
Authorization: {{Authorization}}

{
  "connName": "localhost",
  "namespace": {
    "catalog": "test"
  },
  "sqls": ["create table abc(name varchar(32))"],
  "traceId": "abc"
}

### 数据库 - 数据 - 获取所有插值方法
GET {{baseUrl}}/db/data/loadRandomMethods
Authorization: {{Authorization}}

#####################特殊数据配置数据#######################
### 数据表 - 配置数据(nacos,diamond) - 所有分组信息
GET {{baseUrl}}/db/data/config/groups?connName=lo&schemaName=nacos

### 数据表 - 配置数据 - 分组的 dataIds
GET {{baseUrl}}/db/data/config/dataIds?connName=lo&schemaName=nacos&groupId=scp-st-messagecenter-component

### 数据表 - 配置数据 - 获取配置数据详情
GET {{baseUrl}}/db/data/config/content?connName=lo&schemaName=nacos&groupId=scp-st-messagecenter-component&dataId=scp-st-messagecenter-component-dev.properties

###################代码生成################################
### 数据库 - 代码生成 - 列出所有重命名策略
GET {{baseUrl}}/db/code/renameStrategies
Authorization: {{Authorization}}

### 数据表 - 代码生成 - 生成 javaBean
POST {{baseUrl}}/db/code/build/javaBean
Content-Type: application/json
Authorization: {{Authorization}}

{
  "connName": "localhost",
  "namespace": {
    "catalog": "anta"
  },
  "tableNames": [
    "eims_image",
    "eims_invoices",
    "mct_event_handler"
  ],
  "lombok": true,
  "swagger2": false,
  "persistence": false,
  "serializer": false,
  "packageName": "com.sanri.entity",
  "renameStrategy": "defaultRenameStragtegy"
}


### 数据库 - 代码生成 - mapper 生成 ;  mybatis , tk.mybatis
POST {{baseUrl}}/db/code/build/mapper
Content-Type: application/json
Authorization: {{Authorization}}

{
  "projectName": "c",
  "dataSourceConfig": {
    "connName": "localhost",
    "namespace": {
      "catalog": "anta"
    },
    "tableNames": ["eims_static_language","eims_invoices","eims_image"]
  },
  "packageConfig": {
    "entity": "c.mapper.entity",
    "mapper": "c.mapper",
    "controller": "c.web.controller",
    "service": "c.service",
    "vo": "c.dto.vo",
    "dto": "c.dto",
    "param": "c.dto.param",
    "base": "c",
    "projectName": "c",
    "groupId": "c",
    "artifactId": "c"
  },
  "pluginConfigs": [
    {
      "enable": true,
      "type": "tk.mybatis.mapper.generator.MapperPlugin",
      "properties": {
        "mappers": "tk.mybatis.mapper.common.Mapper",
        "caseSensitive": true,
        "forceAnnotation": true,
        "beginningDelimiter": "`",
        "endingDelimiter": "`",
        "lombok": "Getter,Setter,ToString,Accessors"
      }
    }
  ],
  "filesConfig": {
    "entity": true,
    "xml": true,
    "mapper": true
  },
  "targetRunTime": "MyBatis3Simple",
  "modelType": "FLAT",
  "javaClientType": "XMLMAPPER"
}

### 数据库 - 代码生成 - 写入一个模板
POST {{baseUrl}}/db/code/override
Content-Type: application/json
Authorization: {{Authorization}}

{
  "name": "tables.md.ftl",
  "content": "| 表名 | 说明 |\n| ---- | ---- |\n<#list tables as table>\n| ${table.actualTableName.tableName} |  ${table.remark!}|\n</#list>"
}

### 数据库 - 代码生成 - 列出所有模板
GET {{baseUrl}}/db/code/templates
Authorization: {{Authorization}}

### 数据库 - 代码生成 - 查询某个模板详情
GET {{baseUrl}}/db/code/tables.md.1646637373267.ftl/content
Authorization: {{Authorization}}

### 数据库 - 代码生成 - 建立一个方案
POST {{baseUrl}}/db/code/override
Content-Type: application/json
Authorization: {{Authorization}}

{
  "name": "base.schema",
  "content": "tables.md.1646637373267.ftl"
}

### 数据库 - 代码生成 - 列出所有方案
GET {{baseUrl}}/db/code/schemas
Authorization: {{Authorization}}

### 数据库 - 代码生成 - 列出某个方案的模板列表
GET {{baseUrl}}/db/code/base.schema/templates
Authorization: {{Authorization}}

### 数据库 - 代码生成 - 预览模板代码
POST {{baseUrl}}/db/code/template/code/preview
Content-Type: application/json
Authorization: {{Authorization}}

{
  "template": "tables.md.1646637373267.ftl",
  "connName": "localhost",
  "renameStrategyName": "defaultRenameStragtegy",
  "actualTableName": {
    "namespace": {"catalog": "anta"},
    "tableName": "eims_image"
  },
  "packageConfig": {
    "mapper": "com.sanri.test.mapper"
  }
}

### 数据库 - 代码生成  - 生成代码
POST {{baseUrl}}/db/code/template/code/generator
Content-Type: application/json
Authorization: {{Authorization}}

{
  "renameStrategyName": "defaultRenameStragtegy",
  "templates": [
    "tables.md.1646637373267.ftl"
  ],
  "dataSourceConfig": {
    "connName": "localhost",
    "namespace": {
      "catalog": "anta"
    },
    "tableNames": [
      "eims_image"
    ]
  },
  "packageConfig": {
    "mapper": "com.sanri.test.mapper"
  }
}