### 创建 kafka 连接
POST {{baseUrl}}/kafka/connect/create
Content-Type: application/yaml

connectIdParam:
  module: kafka
  connName: 192.168.72.76_2181
chroot: /hd/kafka
kafka:
  properties:
    sasl:
      jaas:
        config: org.apache.kafka.common.security.plain.PlainLoginModule required username=hd password=hd-kafka;
      mechanism: PLAIN
    security:
      protocol: SASL_PLAINTEXT

### 列出所有的主题信息
GET {{baseUrl}}/kafka/topics?clusterName=192.168.72.42_2181

### 列出主题日志数量
GET {{baseUrl}}/kafka/topic/logSize?clusterName=192.168.72.42_2181&topic=EGSC_SCP_DEVICEMGMT_STATUSTOBROADCAST_TOPIC

### 列出所有的消费组
GET {{baseUrl}}/kafka/groups?clusterName=192.168.72.42_2181

### 列出消费组消费的主题
GET {{baseUrl}}/kafka/group/topics?clusterName=192.168.72.42_2181&group=scp-st-broadcastApp_BC_APP6876

### 消费组情况查询
GET {{baseUrl}}/kafka/group/subscribes?clusterName=192.168.72.42_2181&group=scp-st-broadcastApp_BC_APP6876

### 消费组消费主题的偏移量 offset,logsize,lag
GET {{baseUrl}}/kafka/group/topic/offset?clusterName=192.168.72.42_2181&group=scp-st-broadcastApp_BC_APP6876&topic=EGSC_SCP_DEVICEMGMT_STATUSTOBROADCAST_TOPIC

### 消费组所有主题的偏移量
GET {{baseUrl}}/kafka/group/topics/offset?clusterName=192.168.72.42_2181&group=scp-st-broadcastApp_BC_APP6876

### brokers
GET {{baseUrl}}/kafka/brokers?clusterName=192.168.72.42_2181

### 消费主题最后几条数据
GET {{baseUrl}}/kafka/topic/data/last?clusterName=192.168.72.42_2181&topic=EGSC_SCP_SDC_EVENT_DATA_TOPIC&partition=-1&perPartitionSize=10&serializer=string

### 消费主题数据,并创建索引
GET {{baseUrl}}/kafka/topic/data/consumerDataAndCreateIndex?clusterName=192.168.72.42_2181&topic=EGSC_SCP_SDC_EVENT_DATA_TOPIC&partition=-1&perPartitionSize=10&serializer=string

### 使用索引来查询数据
GET {{baseUrl}}/kafka/topic/data/search?keyword=5236833587864535049012

### 消费主题附近的几条数据
GET {{baseUrl}}/kafka/group/topic/data/nearby?clusterName=192.168.72.42_2181&topic=EGSC_SCP_SDC_EVENT_DATA_TOPIC&partition=0&offset=16090&perPartitionSize=10&serializer=string

### 发送 json 数据
POST {{baseUrl}}/kafka/topic/data/send/json
Content-Type: application/json

### 监控 kafka broker 数据
GET {{baseUrl}}/kafka/monitor/broker?clusterName=192.168.72.42_2181

### 监控 kafka topic 数据
GET {{baseUrl}}/kafka/monitor/topic/EGSC_EGC_MC_APP_ORG_TOPIC?clusterName=192.168.72.42_2181
