### quartz - triggers
GET {{baseUrl}}/quartz/triggers?connName=192.168.60.116&catalog=cc_dt_qa_fssc&tablePrefix=QRTZ_
Authorization: {{Authorization}}

### quartz - trigger
GET {{baseUrl}}/quartz/trigger?connName=192.168.60.116&catalog=cc_dt_qa_fssc&group=DEFAULT&name=voucherPreDelTrigger&classloaderName=job
Authorization: {{Authorization}}

### quartz - pause
GET {{baseUrl}}/quartz/pause?connName=localhost@job&group=default&name=mm&classloaderName=job

### quartz - add job
POST {{baseUrl}}/quartz/localhost@job/editJob
Content-Type: application/json

{
  "name": "mm",
  "group": "default",
  "description": "一个测试添加 job 的功能 ",
  "className": "com.itstyle.quartz.job.CleanUnRelatedImageJob",
  "classloaderName": "job",
  "jobMethodName": "",
  "cron": "* * * * * ? *"
}
