### 看子模块的 resource 能不能加载
GET {{baseUrl}}/index/randomData

### 创建数据库连接
POST {{baseUrl}}/connect/create/database
Content-Type: application/json

{
  "connectIdParam": {
    "module": "database",
    "connName": "lo"
  },
  "connectParam": {
    "host": "10.101.72.43",
    "port": 5432
  },
  "authParam": {
    "username": "postgres",
    "password": "postgres"
  },
  "dbType": "postgresql",
  "schema": "hdsc_db"
}

### 获取所有数据库连接
GET {{baseUrl}}/db/metadata/connections

### 加载连接
POST {{baseUrl}}/db/metadata/connection/load
Content-Type: application/x-www-form-urlencoded

connName=lo

### 获取所有 schema
GET {{baseUrl}}/db/metadata/schemas?connName=lo

### 获取 schema 的所有表
GET {{baseUrl}}/db/metadata/tables?connName=lo&schemaName=hdsc_db

### 标记表-常用标记
GET {{baseUrl}}/db/metadata/extend/mark/tags

### 标记表-标记表
POST {{baseUrl}}/db/metadata/extend/mark/config/tableMark
Content-Type: application/json

[
  {
    "connName": "lo",
    "schemaName": "hdsc_db",
    "tableName": "mct_event_handler",
    "tags": ["biz"]
  }
]

### 标记表-获取表标记
GET {{baseUrl}}/db/metadata/extend/mark/tableTags?connName=lo&schemaName=hdsc_db&tableName=mct_event_handler

### 标记表-查找某个标记的表
GET {{baseUrl}}/db/metadata/extend/mark/tagTables?connName=lo&schemaName=hdsc_db

### 表关系 - 配置表关系
POST {{baseUrl}}/db/metadata/extend/relation/config
Content-Type: application/json

{
  "connName": "lo",
  "schemaName": "hdsc_db",
  "tableRelations": [
    {
      "sourceTableName": "mct.mct_event_handler",
      "targetTableName": "mct.mct_event_record_common",
      "sourceColumnName": "uuid",
      "targetColumnName": "uuid",
      "relation": "ONE_ONE"
    }
  ]
}

###
